sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
scripts:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: Gt6iTM+RsdL5fefRWs39m70UgD5nogwn8nlsJ90o/ldgiL3krL5zvFOuqNNDOHPLOY+ewbG/lg2dQqigAo7w6S+KabmLTuDO4JaDKoCa/PoHFFg9CmiGqu/IlFy6q1oF4mgGzaIwq85eSE1ZiszWeLejRB1BmJr54QMqpayhnGZeEUvQPiBR7jnj2ETPDK7CqOdK61klC/jxmsJiR/nogcDwEiFnCqjqOVfQWWsoOS5k5amjIwWKVewmiOmEWx+ZnZAMGy5+BiZNuedI5RuWPXpVmb4rHvT67QHkQk9OVtACc4EWaLcKkRG0F+RtAkhYi2tXO6GQUBmVDc6xxVRTYHe4nOGdsUWg/RvK/t9CFq+0aHmkpxI/LhctXJ3cTdUvCNz0AuJK7zbrXiZES1cqQlDyhBb/kcHqTnNg7csFA4YsD4OFhzLcJu2gXXZpAOK5IJTREI+IOu/NqbpW+hT1rhdNlPaHEyXG+drer8jfanm4BB+sfRx+fQeZOfXIofAUKATdxDmV9uAL+Pvw4DUCECuL3I+4++MnvGyVudI0MKK2cuWMvCnJgNsvdz+gOcE+flzuZdq+MdxU6JIzkYfgmXcXXuu5hj98KRzIJJVcin8gIMYtPaPZ219QUgtUDR3JO46ozmARx7Mnoa4lO9eoQPG52QSTgOPT/LxjVkcqIxI=
  on: heroku_production
  app: probot-sjackson142
